// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCLqKYEbBPval3a7ybfpGYCTxoA6gtsRPE',
    appId: '1:390804369971:web:ebf6463ac381f5565da946',
    messagingSenderId: '390804369971',
    projectId: 'global-lyrics-c56c8',
    authDomain: 'global-lyrics-c56c8.firebaseapp.com',
    storageBucket: 'global-lyrics-c56c8.firebasestorage.app',
    measurementId: 'G-WK3J9RJB7V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCk3I3Eoug_h_zykT3_vDO6VYwkJVNsmOY',
    appId: '1:390804369971:android:692b8547c288cabe5da946',
    messagingSenderId: '390804369971',
    projectId: 'global-lyrics-c56c8',
    storageBucket: 'global-lyrics-c56c8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCwsssQJoqTbnVSJAIooOFKzZkE7xcSReM',
    appId: '1:390804369971:ios:81aed944d861fcc45da946',
    messagingSenderId: '390804369971',
    projectId: 'global-lyrics-c56c8',
    storageBucket: 'global-lyrics-c56c8.firebasestorage.app',
    iosClientId: '390804369971-huq1ltno5fjlaaelloohcl60uvj5ftfn.apps.googleusercontent.com',
    iosBundleId: 'com.example.globallyrics',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCwsssQJoqTbnVSJAIooOFKzZkE7xcSReM',
    appId: '1:390804369971:ios:81aed944d861fcc45da946',
    messagingSenderId: '390804369971',
    projectId: 'global-lyrics-c56c8',
    storageBucket: 'global-lyrics-c56c8.firebasestorage.app',
    iosClientId: '390804369971-huq1ltno5fjlaaelloohcl60uvj5ftfn.apps.googleusercontent.com',
    iosBundleId: 'com.example.globallyrics',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCLqKYEbBPval3a7ybfpGYCTxoA6gtsRPE',
    appId: '1:390804369971:web:4a014a528991d1b05da946',
    messagingSenderId: '390804369971',
    projectId: 'global-lyrics-c56c8',
    authDomain: 'global-lyrics-c56c8.firebaseapp.com',
    storageBucket: 'global-lyrics-c56c8.firebasestorage.app',
    measurementId: 'G-KHNHHE6400',
  );

}